#!/usr/bin/env crystal
# Real example: Analyze codebase with tree-sitter + DeepSeek + Prolog
# This example shows how to use chiasmus to answer questions about the codebase

require "../src/chiasmus"
require "crig"
require "json"

# Check if DeepSeek API key is available
unless ENV["DEEPSEEK_API_KEY"]?
  puts "⚠️  DEEPSEEK_API_KEY environment variable not set"
  puts "Please set it to run this example:"
  puts "  export DEEPSEEK_API_KEY=your-api-key"
  puts ""
  puts "Using mock mode for demonstration..."
  use_mock = true
else
  use_mock = false
end

module CodebaseAnalyzer
  # Step 1: Analyze the codebase using tree-sitter
  def self.analyze_codebase(files : Array(String)) : String
    puts "📊 Step 1: Analyzing codebase with tree-sitter..."

    # Use the graph tool to extract Prolog facts from the code
    tool = Chiasmus::MCPServer::Tools::GraphTool.new

    result = tool.invoke({
      "files"    => JSON::Any.new(files.map { |f| JSON::Any.new(f) }),
      "analysis" => JSON::Any.new("facts"),
    })

    if result["status"]?.try(&.as_s) == "success"
      prolog_facts = result["result"]?.try(&.as_s) || ""
      puts "  ✓ Extracted #{prolog_facts.lines.size} Prolog facts"
      return prolog_facts
    else
      error = result["error"]?.try(&.as_s) || "Unknown error"
      raise "Failed to analyze codebase: #{error}"
    end
  end

  # Step 2: Create a Prolog program with the facts and a query
  def self.create_prolog_program(facts : String, question : String) : String
    puts "🤖 Step 2: Creating Prolog program for question: #{question}"

    # The facts already include built-in rules for reachability, paths, etc.
    # We just need to add a query based on the question
    program = facts + "\n\n% Query for: #{question}\n"

    # Add a query based on the question type
    if question.includes?("call") || question.includes?("caller") || question.includes?("callee")
      program += "?- findall(Caller, calls(Caller, 'solve'), Callers).\n"
    elsif question.includes?("define") || question.includes?("function")
      program += "?- findall((File,Name,Line), defines(File, Name, function, Line), Definitions).\n"
    elsif question.includes?("reach") || question.includes?("path")
      program += "?- findall((From,To), reaches(From, To), ReachablePairs).\n"
    elsif question.includes?("dead")
      program += "?- findall(Name, dead(Name), DeadFunctions).\n"
    else
      # Generic query - find all function definitions
      program += "?- findall(Name, defines(_, Name, function, _), AllFunctions).\n"
    end

    program
  end

  # Step 3: Use DeepSeek to formulate a better Prolog query
  def self.formulate_query_with_deepseek(agent : Crig::Agent(Crig::Providers::DeepSeek::Model), facts : String, question : String) : String
    puts "🧠 Step 3: Using DeepSeek to formulate Prolog query..."

    prompt = <<-PROMPT
    I have a codebase analyzed as Prolog facts. Here are the facts:

    #{facts.lines.first(50).join("\n")}
    ... (truncated, #{facts.lines.size} total lines)

    Available predicates:
    - defines(File, Name, Kind, Line) - something is defined in a file
    - calls(Caller, Callee) - caller calls callee
    - imports(File, Module, Alias) - file imports a module
    - exports(File, Name) - file exports a name
    - contains(File, Content) - file contains content
    - entry_point(Name) - function is an entry point

    Built-in rules:
    - reaches(A, B) - A can reach B through calls
    - path(A, B, Path) - finds call path from A to B
    - dead(Name) - function is dead code (defined but not called)
    - caller_of(Target, Caller) - convenience for calls(Caller, Target)
    - callee_of(Source, Callee) - convenience for calls(Source, Callee)

    Question: #{question}

    Write a Prolog query (starting with ?-) that answers this question.
    Return ONLY the Prolog query, no explanation.
    PROMPT

    response = agent.prompt(prompt).send
    puts "  ✓ DeepSeek generated query: #{response.strip}"

    # Combine facts with the generated query
    facts + "\n\n% Query generated by DeepSeek for: #{question}\n" + response.strip
  end

  # Step 4: Execute the Prolog query
  def self.execute_prolog_query(program : String) : Chiasmus::Solvers::SolverResult
    puts "⚡ Step 4: Executing Prolog query..."

    # Extract the query (last line starting with ?-)
    lines = program.lines
    query_line = lines.reverse.find { |line| line.strip.starts_with?("?-") }

    unless query_line
      raise "No Prolog query found in program"
    end

    query = query_line.strip.lchop("?-").strip
    prolog_program = lines[0...-1].join("\n")  # Everything except the query line

    # Use the Prolog solver
    solver = Chiasmus::Solvers::PrologSolver.new
    input = Chiasmus::Solvers::PrologSolverInput.new(
      program: prolog_program,
      query: query
    )

    solver.solve(input)
  end

  # Step 5: Format and display results
  def self.display_results(result : Chiasmus::Solvers::SolverResult, question : String)
    puts "\n📋 Results for: #{question}"
    puts "=" * 50

    case result
    when Chiasmus::Solvers::SuccessResult
      success_result = result.as(Chiasmus::Solvers::SuccessResult)

      if success_result.answers.empty?
        puts "No results found."
      else
        puts "Found #{success_result.answers.size} answer(s):"
        success_result.answers.each_with_index do |answer, i|
          puts "  #{i + 1}. #{answer.formatted}"
        end
      end

    when Chiasmus::Solvers::ErrorResult
      error_result = result.as(Chiasmus::Solvers::ErrorResult)
      puts "❌ Error: #{error_result.error}"

    else
      puts "Unexpected result type: #{result.class}"
    end
  end

  # Main analysis workflow
  def self.analyze(question : String, files : Array(String) = ["./src"])
    puts "🔍 Codebase Analysis with Chiasmus + DeepSeek + Prolog"
    puts "=" * 60

    # Step 1: Analyze codebase
    facts = analyze_codebase(files)

    # Step 2: Create agent (real or mock)
    agent = if use_mock
              puts "\n🔄 Using mock agent (no API key)"
              # Create a simple mock agent that returns a predefined query
              MockAgent.new
            else
              puts "\n🚀 Using DeepSeek agent"
              client = Crig::Providers::DeepSeek::Client.builder
                .api_key(ENV["DEEPSEEK_API_KEY"]?)
                .build

              client.agent("deepseek-chat")
                .preamble("You are a code analysis expert. Generate precise Prolog queries.")
                .build
            end

    # Step 3: Formulate query
    program = if use_mock
                create_prolog_program(facts, question)
              else
                formulate_query_with_deepseek(agent, facts, question)
              end

    # Step 4: Execute query
    result = execute_prolog_query(program)

    # Step 5: Display results
    display_results(result, question)

    puts "\n✅ Analysis complete!"
  end

  # Mock agent for demonstration
  class MockAgent
    def prompt(text : String)
      self
    end

    def send : String
      # Return a simple query based on common questions
      "?- findall((File,Name,Line), defines(File, Name, function, Line), Definitions)."
    end
  end
end

# Example questions to ask about the codebase
QUESTIONS = [
  "What functions are defined in the codebase?",
  "What functions call the 'solve' function?",
  "Are there any dead functions (defined but not called)?",
  "What functions can reach the 'formalize' function?",
  "Show me the call graph relationships",
]

# Run the analysis
if ARGV.empty?
  # Use default question
  question = QUESTIONS[0]
  puts "No question provided. Using default: #{question}"
else
  question = ARGV.join(" ")
end

# Analyze current directory
files = Dir.glob("./src/**/*.cr").first(10)  # Limit to 10 files for speed
if files.empty?
  files = ["./src/chiasmus.cr"]  # Fallback
end

begin
  CodebaseAnalyzer.analyze(question, files)
rescue ex
  puts "❌ Error: #{ex.message}"
  puts ex.backtrace.first(5).join("\n") if ENV["DEBUG"]?
end